package com.example.shiftscheduler.models;

import android.provider.ContactsContract;

import com.example.shiftscheduler.R;
import com.example.shiftscheduler.database.DatabaseHelper;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.NavigableSet;
import java.util.Set;

public class FullShift extends ShiftModel implements Serializable {
    private final ShiftTime time = ShiftTime.FULL;
    private final int icon = R.drawable.ic_full;

    /**
     * Constructor.
     * @param shiftID    - will probably be auto-generated by future logic
     * @param date       - date of shift
     * @param employees  - set of assigned employees
     * @param employeesNeeded - maximum employees allowed
     */
    public FullShift(int shiftID, LocalDate date, NavigableSet<EmployeeModel> employees, int employeesNeeded) {
        super(shiftID, date, employees, employeesNeeded);
    }

    /**
     * @return itself
     */
    @Override
    public FullShift toFull() {
        return this;
    }

    /**
     * Verifies this full day shift's employees' qualifications according to specifications
     * @param database - DatabaseHelper object for the current session
     * @return verified
     */
    @Override
    protected boolean verifyEmployeeQualifications(DatabaseHelper database) {
        boolean openQualified = false;
        boolean closeQualified = false;
        List<Boolean> employeeQualifications;
        // check that at least one employee is qualified to open
        // and that at least one employee is qualified to close
        for (EmployeeModel employee : getEmployees()) {
            employeeQualifications = database.getQualifications(employee.getEmployeeID());
            if (!openQualified) {
                openQualified = employeeQualifications.get(0);
            }
            if (!closeQualified) {
                closeQualified = employeeQualifications.get(1);
            }
            if (openQualified && closeQualified) {
                return true;
            }
        }
        return false;
    }
}
