package com.example.shiftscheduler.models;

import com.example.shiftscheduler.R;

import java.time.LocalDate;
import java.util.Set;

public class FullShift extends ShiftModel {
    private final ShiftTime time = ShiftTime.FULL;
    private final int icon = R.drawable.ic_full;

    /**
     * Constructor.
     * @param shiftID    - will probably be auto-generated by future logic
     * @param date       - date of shift
     * @param employees  - set of assigned employees
     * @param maxEmployeeCount - maximum employees allowed
     */
    public FullShift(int shiftID, LocalDate date, Set<EmployeeModel> employees, int maxEmployeeCount) {
        super(shiftID, date, employees, maxEmployeeCount);
    }

    /**
     * @return itself
     */
    @Override
    public FullShift toFull() {
        return this;
    }
}
