package com.example.shiftscheduler.models;

import com.example.shiftscheduler.R;

import java.time.LocalDate;

public class MorningShift extends ShiftModel {
    private final ShiftTime time = ShiftTime.MORNING;
    private final int icon = R.drawable.ic_morning;

    /**
     * Constructor.
     *
     * @param shiftID    - will probably be auto-generated by future logic
     * @param date       - date of shift
     * @param employeeID - ID of the assigned employee
     */
    public MorningShift(int shiftID, LocalDate date, int employeeID) {
        super(shiftID, date, employeeID);
    }

    /**
     * @return itself
     */
    @Override
    public MorningShift toMorning() {
        return this;
    }
}
